import { Invoice, DashboardStats } from './types'

// Demo data for when Supabase isn't configured
export const DEMO_INVOICES: Invoice[] = [
  {
    id: '1',
    invoiceNumber: 'PP-001',
    status: 'paid',
    customerName: 'Sarah Johnson',
    customerEmail: 'sarah@email.com',
    customerPhone: '(555) 123-4567',
    serviceType: 'Drain Cleaning',
    lineItems: [
      { id: '1a', description: 'Drain snake / augering', quantity: 1, unitPrice: 150 },
      { id: '1b', description: 'Camera inspection', quantity: 1, unitPrice: 125 },
      { id: '1c', description: 'Service call fee', quantity: 1, unitPrice: 75 },
    ],
    subtotal: 350,
    tax: 28,
    total: 378,
    notes: 'Kitchen sink drain. Cleared grease buildup.',
    createdAt: '2026-03-25T10:30:00Z',
    paidAt: '2026-03-25T14:22:00Z',
    dueDate: '2026-04-08T10:30:00Z',
    userId: 'demo',
  },
  {
    id: '2',
    invoiceNumber: 'PP-002',
    status: 'paid',
    customerName: 'Mike Torres',
    customerEmail: 'mike.t@email.com',
    customerPhone: '(555) 234-5678',
    serviceType: 'Water Heater',
    lineItems: [
      { id: '2a', description: 'Water heater installation labor', quantity: 1, unitPrice: 350 },
      { id: '2b', description: 'Tank water heater (50 gal)', quantity: 1, unitPrice: 800 },
    ],
    subtotal: 1150,
    tax: 92,
    total: 1242,
    notes: 'Replaced old 40 gal with new 50 gal Rheem.',
    createdAt: '2026-03-22T08:00:00Z',
    paidAt: '2026-03-23T09:15:00Z',
    dueDate: '2026-04-05T08:00:00Z',
    userId: 'demo',
  },
  {
    id: '3',
    invoiceNumber: 'PP-003',
    status: 'unpaid',
    customerName: 'Linda Chen',
    customerEmail: 'linda.chen@email.com',
    customerPhone: '(555) 345-6789',
    serviceType: 'Pipe Repair',
    lineItems: [
      { id: '3a', description: 'Pipe repair labor (per hour)', quantity: 3, unitPrice: 125 },
      { id: '3b', description: 'Copper pipe materials', quantity: 2, unitPrice: 85 },
      { id: '3c', description: 'Pipe fitting / connectors', quantity: 4, unitPrice: 35 },
    ],
    subtotal: 685,
    tax: 54.80,
    total: 739.80,
    notes: 'Repaired corroded copper pipes in basement.',
    createdAt: '2026-03-28T13:00:00Z',
    paidAt: null,
    dueDate: '2026-04-11T13:00:00Z',
    userId: 'demo',
  },
  {
    id: '4',
    invoiceNumber: 'PP-004',
    status: 'unpaid',
    customerName: 'James Wilson',
    customerEmail: 'jwilson@email.com',
    customerPhone: '(555) 456-7890',
    serviceType: 'Bathroom Remodel',
    lineItems: [
      { id: '4a', description: 'Rough-in plumbing labor', quantity: 1, unitPrice: 500 },
      { id: '4b', description: 'Fixture installation (each)', quantity: 3, unitPrice: 175 },
      { id: '4c', description: 'Toilet installation', quantity: 1, unitPrice: 250 },
      { id: '4d', description: 'Shower valve installation', quantity: 1, unitPrice: 300 },
    ],
    subtotal: 1575,
    tax: 126,
    total: 1701,
    notes: 'Master bathroom remodel - full rough-in and fixture install.',
    createdAt: '2026-03-29T09:00:00Z',
    paidAt: null,
    dueDate: '2026-04-12T09:00:00Z',
    userId: 'demo',
  },
  {
    id: '5',
    invoiceNumber: 'PP-005',
    status: 'overdue',
    customerName: 'Patricia Adams',
    customerEmail: 'pat.adams@email.com',
    customerPhone: '(555) 567-8901',
    serviceType: 'Emergency',
    lineItems: [
      { id: '5a', description: 'Emergency service call', quantity: 1, unitPrice: 200 },
      { id: '5b', description: 'Burst pipe repair', quantity: 1, unitPrice: 400 },
      { id: '5c', description: 'After-hours labor (per hour)', quantity: 2, unitPrice: 175 },
    ],
    subtotal: 950,
    tax: 76,
    total: 1026,
    notes: 'Emergency burst pipe in laundry room. Weekend call.',
    createdAt: '2026-03-10T22:00:00Z',
    paidAt: null,
    dueDate: '2026-03-24T22:00:00Z',
    userId: 'demo',
  },
  {
    id: '6',
    invoiceNumber: 'PP-006',
    status: 'paid',
    customerName: 'Robert Kim',
    customerEmail: 'rkim@email.com',
    customerPhone: '(555) 678-9012',
    serviceType: 'Faucet & Fixtures',
    lineItems: [
      { id: '6a', description: 'Faucet installation', quantity: 2, unitPrice: 150 },
      { id: '6b', description: 'Garbage disposal install', quantity: 1, unitPrice: 200 },
    ],
    subtotal: 500,
    tax: 40,
    total: 540,
    notes: 'Kitchen faucet + disposal replacement. Customer supplied faucets.',
    createdAt: '2026-03-18T11:00:00Z',
    paidAt: '2026-03-19T16:30:00Z',
    dueDate: '2026-04-01T11:00:00Z',
    userId: 'demo',
  },
]

export function getDemoStats(): DashboardStats {
  const paid = DEMO_INVOICES.filter(i => i.status === 'paid')
  const unpaid = DEMO_INVOICES.filter(i => i.status !== 'paid')
  const totalRevenue = paid.reduce((sum, i) => sum + i.total, 0)
  const unpaidTotal = unpaid.reduce((sum, i) => sum + i.total, 0)

  return {
    totalRevenue,
    unpaidTotal,
    invoiceCount: DEMO_INVOICES.length,
    paidCount: paid.length,
    avgJobSize: totalRevenue / (paid.length || 1),
    avgPaymentDays: 1.3,
  }
}
